/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: seng.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "seng.pb-c.h"
void   seng_proto__ip_assignment__init
                     (SengProto__IpAssignment         *message)
{
  static SengProto__IpAssignment init_value = SENG_PROTO__IP_ASSIGNMENT__INIT;
  *message = init_value;
}
size_t seng_proto__ip_assignment__get_packed_size
                     (const SengProto__IpAssignment *message)
{
  assert(message->base.descriptor == &seng_proto__ip_assignment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__ip_assignment__pack
                     (const SengProto__IpAssignment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__ip_assignment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__ip_assignment__pack_to_buffer
                     (const SengProto__IpAssignment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__ip_assignment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__IpAssignment *
       seng_proto__ip_assignment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__IpAssignment *)
     protobuf_c_message_unpack (&seng_proto__ip_assignment__descriptor,
                                allocator, len, data);
}
void   seng_proto__ip_assignment__free_unpacked
                     (SengProto__IpAssignment *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__ip_assignment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__ip_assign_ack__init
                     (SengProto__IpAssignACK         *message)
{
  static SengProto__IpAssignACK init_value = SENG_PROTO__IP_ASSIGN_ACK__INIT;
  *message = init_value;
}
size_t seng_proto__ip_assign_ack__get_packed_size
                     (const SengProto__IpAssignACK *message)
{
  assert(message->base.descriptor == &seng_proto__ip_assign_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__ip_assign_ack__pack
                     (const SengProto__IpAssignACK *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__ip_assign_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__ip_assign_ack__pack_to_buffer
                     (const SengProto__IpAssignACK *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__ip_assign_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__IpAssignACK *
       seng_proto__ip_assign_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__IpAssignACK *)
     protobuf_c_message_unpack (&seng_proto__ip_assign_ack__descriptor,
                                allocator, len, data);
}
void   seng_proto__ip_assign_ack__free_unpacked
                     (SengProto__IpAssignACK *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__ip_assign_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__shadow_srv_msg__request_cli_sock_shadowing__init
                     (SengProto__ShadowSrvMsg__RequestCliSockShadowing         *message)
{
  static SengProto__ShadowSrvMsg__RequestCliSockShadowing init_value = SENG_PROTO__SHADOW_SRV_MSG__REQUEST_CLI_SOCK_SHADOWING__INIT;
  *message = init_value;
}
void   seng_proto__shadow_srv_msg__notify_about_close__init
                     (SengProto__ShadowSrvMsg__NotifyAboutClose         *message)
{
  static SengProto__ShadowSrvMsg__NotifyAboutClose init_value = SENG_PROTO__SHADOW_SRV_MSG__NOTIFY_ABOUT_CLOSE__INIT;
  *message = init_value;
}
void   seng_proto__shadow_srv_msg__init
                     (SengProto__ShadowSrvMsg         *message)
{
  static SengProto__ShadowSrvMsg init_value = SENG_PROTO__SHADOW_SRV_MSG__INIT;
  *message = init_value;
}
size_t seng_proto__shadow_srv_msg__get_packed_size
                     (const SengProto__ShadowSrvMsg *message)
{
  assert(message->base.descriptor == &seng_proto__shadow_srv_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__shadow_srv_msg__pack
                     (const SengProto__ShadowSrvMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__shadow_srv_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__shadow_srv_msg__pack_to_buffer
                     (const SengProto__ShadowSrvMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__shadow_srv_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__ShadowSrvMsg *
       seng_proto__shadow_srv_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__ShadowSrvMsg *)
     protobuf_c_message_unpack (&seng_proto__shadow_srv_msg__descriptor,
                                allocator, len, data);
}
void   seng_proto__shadow_srv_msg__free_unpacked
                     (SengProto__ShadowSrvMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__shadow_srv_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__cli_blocker_msg__request_sock_blocking__init
                     (SengProto__CliBlockerMsg__RequestSockBlocking         *message)
{
  static SengProto__CliBlockerMsg__RequestSockBlocking init_value = SENG_PROTO__CLI_BLOCKER_MSG__REQUEST_SOCK_BLOCKING__INIT;
  *message = init_value;
}
void   seng_proto__cli_blocker_msg__close_notify__init
                     (SengProto__CliBlockerMsg__CloseNotify         *message)
{
  static SengProto__CliBlockerMsg__CloseNotify init_value = SENG_PROTO__CLI_BLOCKER_MSG__CLOSE_NOTIFY__INIT;
  *message = init_value;
}
void   seng_proto__cli_blocker_msg__init
                     (SengProto__CliBlockerMsg         *message)
{
  static SengProto__CliBlockerMsg init_value = SENG_PROTO__CLI_BLOCKER_MSG__INIT;
  *message = init_value;
}
size_t seng_proto__cli_blocker_msg__get_packed_size
                     (const SengProto__CliBlockerMsg *message)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__cli_blocker_msg__pack
                     (const SengProto__CliBlockerMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__cli_blocker_msg__pack_to_buffer
                     (const SengProto__CliBlockerMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__CliBlockerMsg *
       seng_proto__cli_blocker_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__CliBlockerMsg *)
     protobuf_c_message_unpack (&seng_proto__cli_blocker_msg__descriptor,
                                allocator, len, data);
}
void   seng_proto__cli_blocker_msg__free_unpacked
                     (SengProto__CliBlockerMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__cli_blocker_reply__init
                     (SengProto__CliBlockerReply         *message)
{
  static SengProto__CliBlockerReply init_value = SENG_PROTO__CLI_BLOCKER_REPLY__INIT;
  *message = init_value;
}
size_t seng_proto__cli_blocker_reply__get_packed_size
                     (const SengProto__CliBlockerReply *message)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__cli_blocker_reply__pack
                     (const SengProto__CliBlockerReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__cli_blocker_reply__pack_to_buffer
                     (const SengProto__CliBlockerReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__CliBlockerReply *
       seng_proto__cli_blocker_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__CliBlockerReply *)
     protobuf_c_message_unpack (&seng_proto__cli_blocker_reply__descriptor,
                                allocator, len, data);
}
void   seng_proto__cli_blocker_reply__free_unpacked
                     (SengProto__CliBlockerReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__cli_blocker_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__shadow_req_reply__init
                     (SengProto__ShadowReqReply         *message)
{
  static SengProto__ShadowReqReply init_value = SENG_PROTO__SHADOW_REQ_REPLY__INIT;
  *message = init_value;
}
size_t seng_proto__shadow_req_reply__get_packed_size
                     (const SengProto__ShadowReqReply *message)
{
  assert(message->base.descriptor == &seng_proto__shadow_req_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__shadow_req_reply__pack
                     (const SengProto__ShadowReqReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__shadow_req_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__shadow_req_reply__pack_to_buffer
                     (const SengProto__ShadowReqReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__shadow_req_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__ShadowReqReply *
       seng_proto__shadow_req_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__ShadowReqReply *)
     protobuf_c_message_unpack (&seng_proto__shadow_req_reply__descriptor,
                                allocator, len, data);
}
void   seng_proto__shadow_req_reply__free_unpacked
                     (SengProto__ShadowReqReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__shadow_req_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   seng_proto__listen_start_confirm__init
                     (SengProto__ListenStartConfirm         *message)
{
  static SengProto__ListenStartConfirm init_value = SENG_PROTO__LISTEN_START_CONFIRM__INIT;
  *message = init_value;
}
size_t seng_proto__listen_start_confirm__get_packed_size
                     (const SengProto__ListenStartConfirm *message)
{
  assert(message->base.descriptor == &seng_proto__listen_start_confirm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t seng_proto__listen_start_confirm__pack
                     (const SengProto__ListenStartConfirm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &seng_proto__listen_start_confirm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t seng_proto__listen_start_confirm__pack_to_buffer
                     (const SengProto__ListenStartConfirm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &seng_proto__listen_start_confirm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SengProto__ListenStartConfirm *
       seng_proto__listen_start_confirm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SengProto__ListenStartConfirm *)
     protobuf_c_message_unpack (&seng_proto__listen_start_confirm__descriptor,
                                allocator, len, data);
}
void   seng_proto__listen_start_confirm__free_unpacked
                     (SengProto__ListenStartConfirm *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &seng_proto__listen_start_confirm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor seng_proto__ip_assignment__field_descriptors[3] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__IpAssignment, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netmask",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__IpAssignment, netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gw_ip",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__IpAssignment, gw_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__ip_assignment__field_indices_by_name[] = {
  2,   /* field[2] = gw_ip */
  0,   /* field[0] = ip */
  1,   /* field[1] = netmask */
};
static const ProtobufCIntRange seng_proto__ip_assignment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor seng_proto__ip_assignment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.IpAssignment",
  "IpAssignment",
  "SengProto__IpAssignment",
  "seng_proto",
  sizeof(SengProto__IpAssignment),
  3,
  seng_proto__ip_assignment__field_descriptors,
  seng_proto__ip_assignment__field_indices_by_name,
  1,  seng_proto__ip_assignment__number_ranges,
  (ProtobufCMessageInit) seng_proto__ip_assignment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__ip_assign_ack__field_descriptors[1] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__IpAssignACK, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__ip_assign_ack__field_indices_by_name[] = {
  0,   /* field[0] = ip */
};
static const ProtobufCIntRange seng_proto__ip_assign_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seng_proto__ip_assign_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.IpAssignACK",
  "IpAssignACK",
  "SengProto__IpAssignACK",
  "seng_proto",
  sizeof(SengProto__IpAssignACK),
  1,
  seng_proto__ip_assign_ack__field_descriptors,
  seng_proto__ip_assign_ack__field_indices_by_name,
  1,  seng_proto__ip_assign_ack__number_ranges,
  (ProtobufCMessageInit) seng_proto__ip_assign_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__shadow_srv_msg__request_cli_sock_shadowing__field_descriptors[3] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__ShadowSrvMsg__RequestCliSockShadowing, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__ShadowSrvMsg__RequestCliSockShadowing, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__ShadowSrvMsg__RequestCliSockShadowing, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__shadow_srv_msg__request_cli_sock_shadowing__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = port */
  2,   /* field[2] = proto */
};
static const ProtobufCIntRange seng_proto__shadow_srv_msg__request_cli_sock_shadowing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor seng_proto__shadow_srv_msg__request_cli_sock_shadowing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.ShadowSrvMsg.RequestCliSockShadowing",
  "RequestCliSockShadowing",
  "SengProto__ShadowSrvMsg__RequestCliSockShadowing",
  "seng_proto",
  sizeof(SengProto__ShadowSrvMsg__RequestCliSockShadowing),
  3,
  seng_proto__shadow_srv_msg__request_cli_sock_shadowing__field_descriptors,
  seng_proto__shadow_srv_msg__request_cli_sock_shadowing__field_indices_by_name,
  1,  seng_proto__shadow_srv_msg__request_cli_sock_shadowing__number_ranges,
  (ProtobufCMessageInit) seng_proto__shadow_srv_msg__request_cli_sock_shadowing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__shadow_srv_msg__notify_about_close__field_descriptors[1] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__ShadowSrvMsg__NotifyAboutClose, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__shadow_srv_msg__notify_about_close__field_indices_by_name[] = {
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange seng_proto__shadow_srv_msg__notify_about_close__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seng_proto__shadow_srv_msg__notify_about_close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.ShadowSrvMsg.NotifyAboutClose",
  "NotifyAboutClose",
  "SengProto__ShadowSrvMsg__NotifyAboutClose",
  "seng_proto",
  sizeof(SengProto__ShadowSrvMsg__NotifyAboutClose),
  1,
  seng_proto__shadow_srv_msg__notify_about_close__field_descriptors,
  seng_proto__shadow_srv_msg__notify_about_close__field_indices_by_name,
  1,  seng_proto__shadow_srv_msg__notify_about_close__number_ranges,
  (ProtobufCMessageInit) seng_proto__shadow_srv_msg__notify_about_close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__shadow_srv_msg__field_descriptors[2] =
{
  {
    "reqShadow",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SengProto__ShadowSrvMsg, msg_case),
    offsetof(SengProto__ShadowSrvMsg, reqshadow),
    &seng_proto__shadow_srv_msg__request_cli_sock_shadowing__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeNotify",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SengProto__ShadowSrvMsg, msg_case),
    offsetof(SengProto__ShadowSrvMsg, closenotify),
    &seng_proto__shadow_srv_msg__notify_about_close__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__shadow_srv_msg__field_indices_by_name[] = {
  1,   /* field[1] = closeNotify */
  0,   /* field[0] = reqShadow */
};
static const ProtobufCIntRange seng_proto__shadow_srv_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor seng_proto__shadow_srv_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.ShadowSrvMsg",
  "ShadowSrvMsg",
  "SengProto__ShadowSrvMsg",
  "seng_proto",
  sizeof(SengProto__ShadowSrvMsg),
  2,
  seng_proto__shadow_srv_msg__field_descriptors,
  seng_proto__shadow_srv_msg__field_indices_by_name,
  1,  seng_proto__shadow_srv_msg__number_ranges,
  (ProtobufCMessageInit) seng_proto__shadow_srv_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__cli_blocker_msg__request_sock_blocking__field_descriptors[4] =
{
  {
    "port",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__RequestSockBlocking, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__RequestSockBlocking, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mr_enclave",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__RequestSockBlocking, mr_enclave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mr_signer",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__RequestSockBlocking, mr_signer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__cli_blocker_msg__request_sock_blocking__field_indices_by_name[] = {
  2,   /* field[2] = mr_enclave */
  3,   /* field[3] = mr_signer */
  0,   /* field[0] = port */
  1,   /* field[1] = proto */
};
static const ProtobufCIntRange seng_proto__cli_blocker_msg__request_sock_blocking__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor seng_proto__cli_blocker_msg__request_sock_blocking__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.CliBlockerMsg.RequestSockBlocking",
  "RequestSockBlocking",
  "SengProto__CliBlockerMsg__RequestSockBlocking",
  "seng_proto",
  sizeof(SengProto__CliBlockerMsg__RequestSockBlocking),
  4,
  seng_proto__cli_blocker_msg__request_sock_blocking__field_descriptors,
  seng_proto__cli_blocker_msg__request_sock_blocking__field_indices_by_name,
  1,  seng_proto__cli_blocker_msg__request_sock_blocking__number_ranges,
  (ProtobufCMessageInit) seng_proto__cli_blocker_msg__request_sock_blocking__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__cli_blocker_msg__close_notify__field_descriptors[2] =
{
  {
    "port",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__CloseNotify, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerMsg__CloseNotify, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__cli_blocker_msg__close_notify__field_indices_by_name[] = {
  0,   /* field[0] = port */
  1,   /* field[1] = proto */
};
static const ProtobufCIntRange seng_proto__cli_blocker_msg__close_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor seng_proto__cli_blocker_msg__close_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.CliBlockerMsg.CloseNotify",
  "CloseNotify",
  "SengProto__CliBlockerMsg__CloseNotify",
  "seng_proto",
  sizeof(SengProto__CliBlockerMsg__CloseNotify),
  2,
  seng_proto__cli_blocker_msg__close_notify__field_descriptors,
  seng_proto__cli_blocker_msg__close_notify__field_indices_by_name,
  1,  seng_proto__cli_blocker_msg__close_notify__number_ranges,
  (ProtobufCMessageInit) seng_proto__cli_blocker_msg__close_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor seng_proto__cli_blocker_msg__field_descriptors[2] =
{
  {
    "sockBlock",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SengProto__CliBlockerMsg, msg_case),
    offsetof(SengProto__CliBlockerMsg, sockblock),
    &seng_proto__cli_blocker_msg__request_sock_blocking__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeNotify",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SengProto__CliBlockerMsg, msg_case),
    offsetof(SengProto__CliBlockerMsg, closenotify),
    &seng_proto__cli_blocker_msg__close_notify__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__cli_blocker_msg__field_indices_by_name[] = {
  1,   /* field[1] = closeNotify */
  0,   /* field[0] = sockBlock */
};
static const ProtobufCIntRange seng_proto__cli_blocker_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor seng_proto__cli_blocker_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.CliBlockerMsg",
  "CliBlockerMsg",
  "SengProto__CliBlockerMsg",
  "seng_proto",
  sizeof(SengProto__CliBlockerMsg),
  2,
  seng_proto__cli_blocker_msg__field_descriptors,
  seng_proto__cli_blocker_msg__field_indices_by_name,
  1,  seng_proto__cli_blocker_msg__number_ranges,
  (ProtobufCMessageInit) seng_proto__cli_blocker_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue seng_proto__cli_blocker_reply__replies__enum_values_by_number[5] =
{
  { "DENIED", "SENG_PROTO__CLI_BLOCKER_REPLY__REPLIES__DENIED", 0 },
  { "GRANTED", "SENG_PROTO__CLI_BLOCKER_REPLY__REPLIES__GRANTED", 1 },
  { "IN_USE", "SENG_PROTO__CLI_BLOCKER_REPLY__REPLIES__IN_USE", 2 },
  { "WAS_NOT_BLOCKED", "SENG_PROTO__CLI_BLOCKER_REPLY__REPLIES__WAS_NOT_BLOCKED", 3 },
  { "NOW_UNLBOCKED", "SENG_PROTO__CLI_BLOCKER_REPLY__REPLIES__NOW_UNLBOCKED", 4 },
};
static const ProtobufCIntRange seng_proto__cli_blocker_reply__replies__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex seng_proto__cli_blocker_reply__replies__enum_values_by_name[5] =
{
  { "DENIED", 0 },
  { "GRANTED", 1 },
  { "IN_USE", 2 },
  { "NOW_UNLBOCKED", 4 },
  { "WAS_NOT_BLOCKED", 3 },
};
const ProtobufCEnumDescriptor seng_proto__cli_blocker_reply__replies__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "seng_proto.CliBlockerReply.Replies",
  "Replies",
  "SengProto__CliBlockerReply__Replies",
  "seng_proto",
  5,
  seng_proto__cli_blocker_reply__replies__enum_values_by_number,
  5,
  seng_proto__cli_blocker_reply__replies__enum_values_by_name,
  1,
  seng_proto__cli_blocker_reply__replies__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor seng_proto__cli_blocker_reply__field_descriptors[1] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SengProto__CliBlockerReply, reply),
    &seng_proto__cli_blocker_reply__replies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__cli_blocker_reply__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange seng_proto__cli_blocker_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seng_proto__cli_blocker_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.CliBlockerReply",
  "CliBlockerReply",
  "SengProto__CliBlockerReply",
  "seng_proto",
  sizeof(SengProto__CliBlockerReply),
  1,
  seng_proto__cli_blocker_reply__field_descriptors,
  seng_proto__cli_blocker_reply__field_indices_by_name,
  1,  seng_proto__cli_blocker_reply__number_ranges,
  (ProtobufCMessageInit) seng_proto__cli_blocker_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue seng_proto__shadow_req_reply__replies__enum_values_by_number[2] =
{
  { "DENIED", "SENG_PROTO__SHADOW_REQ_REPLY__REPLIES__DENIED", 0 },
  { "GRANTED", "SENG_PROTO__SHADOW_REQ_REPLY__REPLIES__GRANTED", 1 },
};
static const ProtobufCIntRange seng_proto__shadow_req_reply__replies__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex seng_proto__shadow_req_reply__replies__enum_values_by_name[2] =
{
  { "DENIED", 0 },
  { "GRANTED", 1 },
};
const ProtobufCEnumDescriptor seng_proto__shadow_req_reply__replies__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "seng_proto.ShadowReqReply.Replies",
  "Replies",
  "SengProto__ShadowReqReply__Replies",
  "seng_proto",
  2,
  seng_proto__shadow_req_reply__replies__enum_values_by_number,
  2,
  seng_proto__shadow_req_reply__replies__enum_values_by_name,
  1,
  seng_proto__shadow_req_reply__replies__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor seng_proto__shadow_req_reply__field_descriptors[1] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SengProto__ShadowReqReply, reply),
    &seng_proto__shadow_req_reply__replies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__shadow_req_reply__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange seng_proto__shadow_req_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seng_proto__shadow_req_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.ShadowReqReply",
  "ShadowReqReply",
  "SengProto__ShadowReqReply",
  "seng_proto",
  sizeof(SengProto__ShadowReqReply),
  1,
  seng_proto__shadow_req_reply__field_descriptors,
  seng_proto__shadow_req_reply__field_indices_by_name,
  1,  seng_proto__shadow_req_reply__number_ranges,
  (ProtobufCMessageInit) seng_proto__shadow_req_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue seng_proto__listen_start_confirm__replies__enum_values_by_number[2] =
{
  { "FAILED", "SENG_PROTO__LISTEN_START_CONFIRM__REPLIES__FAILED", 0 },
  { "NOW_LISTENING", "SENG_PROTO__LISTEN_START_CONFIRM__REPLIES__NOW_LISTENING", 1 },
};
static const ProtobufCIntRange seng_proto__listen_start_confirm__replies__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex seng_proto__listen_start_confirm__replies__enum_values_by_name[2] =
{
  { "FAILED", 0 },
  { "NOW_LISTENING", 1 },
};
const ProtobufCEnumDescriptor seng_proto__listen_start_confirm__replies__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "seng_proto.ListenStartConfirm.Replies",
  "Replies",
  "SengProto__ListenStartConfirm__Replies",
  "seng_proto",
  2,
  seng_proto__listen_start_confirm__replies__enum_values_by_number,
  2,
  seng_proto__listen_start_confirm__replies__enum_values_by_name,
  1,
  seng_proto__listen_start_confirm__replies__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor seng_proto__listen_start_confirm__field_descriptors[1] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SengProto__ListenStartConfirm, reply),
    &seng_proto__listen_start_confirm__replies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned seng_proto__listen_start_confirm__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange seng_proto__listen_start_confirm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor seng_proto__listen_start_confirm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "seng_proto.ListenStartConfirm",
  "ListenStartConfirm",
  "SengProto__ListenStartConfirm",
  "seng_proto",
  sizeof(SengProto__ListenStartConfirm),
  1,
  seng_proto__listen_start_confirm__field_descriptors,
  seng_proto__listen_start_confirm__field_indices_by_name,
  1,  seng_proto__listen_start_confirm__number_ranges,
  (ProtobufCMessageInit) seng_proto__listen_start_confirm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
